# import the necessary components first
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from string import Template
from subscribeDAO import select_all_users, select_all_users_where_country
from helpers import dict_factory


""" every time the cases update in table
    send an email to all the subscribers from the database
    the function is called in dbQRYsCoronaCases only if the tables update
"""
def email_to_subscribers(country, new, totalCases):

  subscribers = {}
  subscribers =  select_all_users_where_country(country)
  
  # if subscribers and tblValues contain data
  if bool(subscribers):
    for row in subscribers:
      emailAdress = row['emailAdress']
      name = row['Name']
      send_email(emailAdress, name, country, new, totalCases)
  return


port = 25
smtp_server = "smtp.sendgrid.net"
login = "apikey" # paste your login generated by Mailtrap
password = "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" # paste your password generated by Mailtrap
sender_email = "iordanescu.sergiu@gmail.com"
def send_email(emailAdress, username, country, newCases, totalCases):
  #receiver_email = "sergiu.cl.iordanescu@gmail.com"
  receiver_email = emailAdress
  message = MIMEMultipart("alternative")
  message["Subject"] = "Corona Cases"
  message["From"] = sender_email
  message["To"] = receiver_email
  # write the plain text part
  text = """\
  Hi, Boss!"""
  # write the HTML part
  html = """\
  <html>
    <body>
      <p>Hi {name},<p><br>
      <p>below you can find the new number of Corona cases in {country}:</p><br>
      <p style="color:red;">New Cases: {newCases}</p>
      <p>Total Cases: {totalCases}</p><br>
      <p>Best Regards,</p>
      <p>Sergiu</p>
    </body>
  </html>
  """.format(name=username, newCases=newCases, country=country, totalCases=totalCases)

  # convert both parts to MIMEText objects and add them to the MIMEMultipart message
  part1 = MIMEText(text, "plain")
  part2 = MIMEText(html, "html")
  message.attach(part1)
  message.attach(part2)

  # send your email
  with smtplib.SMTP(smtp_server, port) as server:
      server.login(login, password)
      server.sendmail(
          sender_email, receiver_email, message.as_string()
      )