# import the necessary components first
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from string import Template
from dbQRYsSubscribe import select_all_users
from helpers import dict_factory
import sqlite3
#from dbQRYsCoronaCases import select_cases


""" every time the cases update in table
    send an email to all the subscribers from the database
    the function is called in dbQRYsCoronaCases only if the tables update
"""
def email_to_subscribers():

  subscribers = {}
  subscribers =  select_all_users()
  # Configure SQLite database
  conn = sqlite3.connect('coronaDatabase.db')
  conn.row_factory = dict_factory
  cursor = conn.cursor()
  sql_command = """SELECT * FROM casesWorld;"""
  cursor.execute(sql_command)
  tblValues = cursor.fetchall()
  
  # if subscribers and tblValues contain data
  if bool(subscribers):
    if bool(tblValues):
      # get the values from country, email and name from every row in dict
      for row in subscribers:
        country = row['country']
        emailAdress = row['emailAdress']
        name = row['Name']
        # go through the values from tblValues
        # if country from tblValues is country from subscribers
        # send an email to the user with the data from that country
        for data in tblValues:
          if data['country'] == country:
            send_email(emailAdress, name, country, data['new'], data['totalCases'])
  return


port = 25
smtp_server = "smtp.sendgrid.net"
login = "apikey" # paste your login generated by Mailtrap
password = "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" # paste your password generated by Mailtrap
sender_email = "iordanescu.sergiu@gmail.com"
def send_email(emailAdress, username, country, newCases, totalCases):
  #receiver_email = "sergiu.cl.iordanescu@gmail.com"
  receiver_email = emailAdress
  message = MIMEMultipart("alternative")
  message["Subject"] = "Corona Cases"
  message["From"] = sender_email
  message["To"] = receiver_email
  # write the plain text part
  text = """\
  Hi, Boss!"""
  # write the HTML part
  html = """\
  <html>
    <body>
      <p>Hi {name},<br>
      <p>Below you can find the new number of Corona cases in {country}</p><br>
      <p style="color:red;">New Cases: {newCases}</p>
      <p>Total Cases: {totalCases}</p>
    </body>
  </html>
  """.format(name=username, newCases=newCases, country=country, totalCases=totalCases)

  # convert both parts to MIMEText objects and add them to the MIMEMultipart message
  part1 = MIMEText(text, "plain")
  part2 = MIMEText(html, "html")
  message.attach(part1)
  message.attach(part2)

  # send your email
  with smtplib.SMTP(smtp_server, port) as server:
      server.login(login, password)
      server.sendmail(
          sender_email, receiver_email, message.as_string()
      )