# import the necessary components first
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

port = 25 
smtp_server = "smtp.sendgrid.net"
login = "apikey" # paste your login generated by Mailtrap
password = "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" # paste your password generated by Mailtrap
sender_email = "atanasache11@gmail.com"
receiver_email = "iordanescu.sergiu@gmail.com"
message = MIMEMultipart("alternative")
message["Subject"] = "Corona Cases"
message["From"] = sender_email
message["To"] = receiver_email
# write the plain text part
text = """\
Hi, Boss!"""
# write the HTML part
html = """\
<html>
  <body>
    <p>Hi name,<br>
    <p>Below you can find the new number of Corona cases</p>
    <p>New Cases: </p>
    <p>New Deaths: </p>
  </body>
</html>
"""
# convert both parts to MIMEText objects and add them to the MIMEMultipart message
part1 = MIMEText(text, "plain")
part2 = MIMEText(html, "html")
message.attach(part1)
message.attach(part2)

# send your email
with smtplib.SMTP(smtp_server, port) as server:
    server.login(login, password)
    server.sendmail(
        sender_email, receiver_email, message.as_string()
    )
print('Sent') 